### ISSUE TITLE
mechanize error

### ISSUE THREAD

**Issue by charlesrobison** [isaacmiller2004/GetYahooFBBData#3]
Getting the following when running the updated script:

line 2424, in _find_control
    raise ControlNotFoundError("no control matching " + description)
mechanize._form_controls.ControlNotFoundError: no control matching name 'passwd'

**Comment by cdenny** [comment]
I ran across this as well.  Its due to an update in form  it appears they updated the name of the password field.    The field name went from passwd to password.   updating that appears to fix the issue

**Comment by charlesrobison** [comment]
That did the trick.  Too bad this isn't ported to Python 3.  I'm able to run it with a Python 2 virtual environment though.  Getting this error now:

Gathering Data...
Loading page 1
Traceback (most recent call last):
  File "GetYahooFBBData.py", line 211, in <module>
    main()
  File "GetYahooFBBData.py", line 83, in main
    tmp = str(dataList[pNum+i].findAll(text=True))
IndexError: list index out of range

**Comment by charlesrobison** [comment]
Had this working with 'password', not it's not working again.  Getting the same error:

Getting the following when running the updated script:

line 2424, in _find_control
raise ControlNotFoundError("no control matching " + description)
mechanize._form_controls.ControlNotFoundError: no control matching name 'password'

How can I look to see if the field name changed again?

**Comment by cdenny** [comment]
go to login.yahoo.com, and get to the page where you enter your password.   right click in the password field and click 'inspect element' (chrome).  You should get a highlighted section.  look for 'name='    the value of name should be what you want.

I checked this morning, and I"m currently seeing password is correct

**Comment by charlesrobison** [comment]
I wonder what could be causing that error then.  Are you able to run this okay @cdenny ?

**Comment by cdenny** [comment]
I was able to run it this morning.  with out issue.  here is the code I have in that section

`cj = cookielib.CookieJar()
	br = mechanize.Browser()
	br.set_handle_robots(False)
	br.addheaders = [('User-agent', 'Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US; rv:1.9.0.6')]
	br.set_cookiejar(cj)
	br.open("https://login.yahoo.com/")
	br.select_form(nr=0)
	br.form["username"] = username
	submit_response = br.submit()
	br.select_form(nr=0)
	br.form["password"] = password
	br.submit()`

**Comment by charlesrobison** [comment]
Weird - still getting the error:

line 2424, in _find_control
    raise ControlNotFoundError("no control matching " + description)
mechanize._form_controls.ControlNotFoundError: no control matching name 'password'

Wonder if it has to do with Yahoo's authentication.

**Comment by charlesrobison** [comment]
Yep, that was it.  I had to go into the account settings and disable the account key.  Good to go now.
